Основные типы и операции с тензорами в PyTorch

In [ ]:
import torch

In [ ]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

In [ ]:
x = torch.FloatTensor(2, 2)
x.zero_()
x

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
y = torch.zeros_like(x)
# проверка равенства
torch.allclose(x, y)

True

In [ ]:
# случайное распределение
x = torch.randn((2,3))
x.random_(0, 10)                      # Дискретное равномерно U[0, 10]
x.uniform_(0, 1)                      # Равномерно U[0, 1]
x.normal_(mean=0, std=1)              # Нормальное со средним 0 и дисперсией 1
x.bernoulli_(p=0.5)                   # bernoulli with parameter p

In [ ]:
# решейпы
a = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
b = a.view(3, 2)
a.reshape(-1)
a.permute(1, 0)   # не то же самое что view!
a.transpose(1, 2)

In [ ]:
# изменение типа
a.type_as(torch.IntTensor())
a.to(torch.int32)
a.to(torch.uint8)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)

In [ ]:
z# операции
a = torch.FloatTensor([[1, 2, 1], [2, 1, 2]])
b = torch.FloatTensor([[2, 1, 2], [1, 1, 1]])

a * b          # поэлементное умножение
a / b          # поэлементное деление
a == b         # поэлементное сравнение
a[a > b]       # индексация по логической маске
a.abs()        # поэлементное применение функции модуль
a.sum(dim=0)   # сумма по оси dim
a.mean(dim=0)  # среднее по оси dim
a.max(0)       # максимумы по оси + их индексы в строке

Операции всегда производятся по той оси, которая исчезнет после применения операции.

In [ ]:
# фиктивные оси
a[:, :, None]

tensor([[[1.],
         [2.],
         [1.]],

        [[2.],
         [1.],
         [2.]]])

In [ ]:
# нормализации тензора
mean = a.mean(1)
std = a.std(1)
a -= mean.reshape(-1,1)
a /= std.reshape(-1,1)

In [ ]:
# векторные операции

a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

a.dot(b)       # скалярное произведение векторов
a @ b          # скалярное произведение векторов

tensor(-141.)

In [ ]:
# матричные операции

a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

a.mm(b)        # матричное произведение
a @ b          # матричное произведение

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [ ]:
# конвертация
import numpy as np

a = np.random.rand(2, 2)
b = torch.from_numpy(a)
x = b.numpy()

In [ ]:
# CUDA

x.is_cuda
x = x.cuda()
x = x.cpu()
torch.cuda.empty_cache()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = x.to(device)

Advanced operations

In [1]:
import torch

# вместо среза
m = torch.randn(2,3,4)
# torch.narrow(tensor, dimension, start, length)
torch.narrow(m,1,2,1)

tensor([[[-0.1475, -2.0303,  0.8303, -1.3733]],

        [[-0.3598,  1.6185, -0.2450, -0.5121]]])

In [ ]:
m = torch.randn(3,2)
n = torch.randn(2,2)
# матричное умножение
torch.matmul(m,n)

In [ ]:
torch.where(m<0,m,n)        # где True - m, иначе - n
torch.all(m,0)              # все ли по этому dim True
n = m.squeeze(dim = 0)      # убирает указанное dim
m.unbind(dim = 1)           # возвращает tuple тензоров по указанному dim

torch.tensor.half()         # перевод в int16 -> работает быстрее

In [3]:
# торч может умножать и прибавлять по батчам
a = torch.randn((8, 5, 5))
b = torch.randn((5, 5))

(a @ b).shape

torch.Size([8, 5, 5])

In [4]:
(a + b).shape        # прибавляет к каждому из 8

torch.Size([8, 5, 5])

In [25]:
# выбор значения из нужного канала
n_samples = 1
dim = 0
src = torch.randn((4, 4, 6))
index = torch.randint(low = 0, high = 4, size = (n_samples, 4, 6))
out = torch.gather(src, dim=dim, index=index)

In [29]:
# перевод обратно в исходные тензоры
torch.zeros((4, 4, 6)).scatter_add_(dim=dim, index=index, src=out).shape

torch.Size([4, 4, 6])

In [34]:
import torch.functional as F
F.unfold()     # im2col
F.fold()       # col2im

Распространенные ошибки при обучении

1. Использование softmax и CrossEntropyLoss() - в ней уже считается softmax
2. Использование bias и BatchNorm() - аналогично
